---
title: "Integrate fast CRV3 for lm()"
author: "Alexander Fischer"
date: "4/23/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example: 

```{r, warning = FALSE, message = FALSE}
set.seed(98765)
library(clubSandwich)
library(clusterjack)

# few large clusters (around 10000 obs)
N <- 1000
N_G1 <-10
data <- fwildclusterboot:::create_data(
  N = N,
  N_G1 = N_G1,
  icc1 = 0.8,
  N_G2 = 10,
  icc2 = 0.8,
  numb_fe1 = 10,
  numb_fe2 = 10,
  seed = 12
)

lm_fit <- lm(proposition_vote ~ treatment  + log_income , data = data)

#clubSandwich::vcovCR(obj = lm_fit, cluster= data$group_id1, type = "CR3")

res <- clubSandwich:::vcov_CR(
  obj = lm_fit, 
  cluster= data$group_id1, 
  type = "CR3f"
)

res2 <- clusterjack::vcovJN(
  model = lm_fit, 
  clustid= data$group_id1
)

all.equal(as.matrix(res), res2, check.attributes = FALSE)
```

## Comparison to `CR3`, check that all methods work

```{r, warning = FALSE, error = FALSE}

resCR3 <- clubSandwich:::vcov_CR(
  obj = lm_fit, 
  cluster= data$group_id1, 
  type = "CR3"
)

```

Confidence Interval: 

```{r}
clubSandwich::conf_int(
  obj = lm_fit, 
  vcov = res,
  test = "Satterthwaite"
)

clubSandwich::conf_int(
  obj = lm_fit, 
  vcov = resCR3,
  test = "Satterthwaite"
)
```

`coef_table()`:

```{r}
clubSandwich::coef_test(
  obj = lm_fit, 
  vcov = res,
  test = "Satterthwaite"
)

clubSandwich::coef_test(
  obj = lm_fit, 
  vcov = resCR3,
  test = "Satterthwaite"
)
```

`Wald_test()`:

```{r}
clubSandwich::Wald_test(
  obj = lm_fit, 
  constraints = clubSandwich::constrain_zero(2:3, coef(lm_fit)),
  vcov = res
)

clubSandwich::Wald_test(
  obj = lm_fit, 
  constraints = clubSandwich::constrain_zero(2:3, coef(lm_fit)),
  vcov = resCR3
)
```


## Notes: 

- cheat in small sample correction (not really using CR-adjustments.R)
- documentation - add note that `CR3f` only for `lm()`
- `vcovCR` still gets stuck somewhere, that's why I am using `clubSandwich::vcov_CR` here

